# Generated by Django 4.2.8 on 2024-01-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_customer_details_alter_customer_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='responsible',
            field=models.CharField(default='', max_length=255),
        ),
    ]
