# Generated by Django 4.2.8 on 2024-01-01 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0004_alter_object_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
    ]
