# Generated by Django 4.2.8 on 2024-01-03 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0005_alter_object_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='act',
        ),
        migrations.RemoveField(
            model_name='request',
            name='department',
        ),
        migrations.RemoveField(
            model_name='request',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='responsible_customer',
        ),
        migrations.AlterField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Performer',
        ),
    ]
