# Generated by Django 4.2.8 on 2024-01-03 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_remove_request_act_remove_request_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
