# Generated by Django 4.2.8 on 2024-01-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_request_options_remove_request_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Region_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.region')),
            ],
            options={
                'verbose_name': 'Наименование региона',
                'verbose_name_plural': 'Наименования регионов',
            },
        ),
    ]
