# Generated by Django 4.2.8 on 2024-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_region_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region_name',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
