# Generated by Django 4.2.8 on 2024-01-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_region_options_customer_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.TextField()),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.customer')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['title'],
            },
        ),
    ]
