# Generated by Django 4.2.8 on 2024-01-20 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_files_facilityimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-created'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='files',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
