# Generated by Django 4.2.8 on 2024-01-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_alter_files_options_files_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityimg',
            options={'ordering': ['-file__created'], 'verbose_name': 'Фото объектов', 'verbose_name_plural': 'Фото объектов'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['created'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
