# Generated by Django 4.2.8 on 2024-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_facilityimg_options_alter_files_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='lastServiceDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата последнего обслуживания'),
        ),
        migrations.AddField(
            model_name='facility',
            name='openDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Открытия'),
        ),
    ]
